### PR TITLE
General Efficency patches

### PR DESCRIPTION
**Pull request by brutalgg**
Updates include:

- Removal of a daemon process not being used
- Consolidation of apt-get calls to decrease duplicated container layer storage and reduce image size by 400mb.
- Updates to dockerfile structure to conform to best practice such as removal of deprecated 'maintainer' and modification of bash expansion variables.

### CODE REVIEW

**Comment by brutalgg** [comment]
500Mb. Found an orphaned go gzip in the container.

**Comment by AlexisAhmed** [comment]
The build contains errors, will roll back to previous version and work on the Dockerfile.

**Comment by brutalgg** [comment]
What errors are you encountering. I built the file without issue but maybe I can help troubleshoot what’s going on?

**Comment by Protech2014** [comment]
Big Thanks...
Unending maze

**Pull request merged**
